### ISSUE TITLE
LogManager.GetLogger<T>() and LogManager.GetCurrentClassLogger()

### ISSUE THREAD

**Issue by georgiosd** [Abc-Arbitrage/ZeroLog#22]
Hi!

Great job!
Would you accept a PR for these methods?

Thanks

**Comment by ltrzesniewski** [comment]
Hi and thanks!

I'm actually surprised we don't have a `GetLogger<T>()` convenience method yet, given that'd be just one line of code: `GetLogger<T>() => GetLogger(typeof(T));`, so yes that would be a welcome addition.

But how would you implement `GetCurrentClassLogger()`? You can't use `[CallerMemberName]` here and performing a stack walk sounds a bit overkill for such a method.

**Comment by georgiosd** [comment]
I would look at how NLog does it :)
Probably a stack walk - it's only called once so personally speaking that sounds OK.
`GetLogger<T>` seems just as good though

**Comment by MendelMonteiro** [comment]
The implementation in NLog:
https://github.com/NLog/NLog/blob/ab141c4c39a0b8272875acfed10db9dc0b5d82a0/src/NLog/Internal/StackTraceUsageUtils.cs

**Comment by georgiosd** [comment]
Yikes! I retract my last statement, it's not worth it :D

**Comment by georgiosd** [comment]
Nice @ltrzesniewski thanks! Never got round to it, sorry :(

**Comment by ltrzesniewski** [comment]
No problem, that was one line of code after all :wink:
