### ISSUE TITLE
Add support for FormattableString

### ISSUE THREAD

**Issue by damageboy** [Abc-Arbitrage/ZeroLog#24]
I think it would be a nice addition to the arsenal of ZeroLog to support the somewhat unknown c# interpolated string feature called `ForamttableString`.

This would basically allow users to call ZeroLog with interpolated strings:
```
log.InfoInterpolated($"Tomorrow ({tomorrow}) will occur in {numberOfSecondsUntilTomorrow} seconds");
```

The theory behind this is that ZeroLog would get a [FormattableString](https://docs.microsoft.com/en-gb/dotnet/api/system.formattablestring?view=netframework-4.7.1) instance fed into the `*Interpolated` variants of the logging functions that would have to be added to ZeroLog and to the StringFormatter project.

The reason behind adding yet another overload for this purpose is that apprently the c# compiler has a feature/issue where having two functions that only differ by having a string/FormattableString parameter leads to the string variant being always selected by the compiler:

https://github.com/dotnet/roslyn/issues/46

http://blog.engdahls.dk/2016/08/how-to-overload-string-and.html

Any thoughts about this?

**Comment by ltrzesniewski** [comment]
The problem about `FormattableString` is that using it would necessarily allocate, while the ZeroLog API is built to avoid allocations at all costs.

We could perhaps support it without allocating by rewriting the code with a Fody addin (this would rewrite the `FormattableString` to regular `Append` calls).

**Comment by damageboy** [comment]
@ltrzesniewski ah, thanks for the comment.
I didn't think about what the compiler actually does for preparing the FormattalbeString object before passing it to the function.

So in essence, the compiler is re-writing the code to allocate the FormattableString object at the call site?

**Comment by ltrzesniewski** [comment]
Yes, it allocates the `FormattableString`, plus an `object[]` array to hold the values, and it needs to box the values when they're value types.

See [here](https://sharplab.io/#v2:D4AQDABCCMDcCwAoEBmKAmCBhCBvJEhUaIALBALIAUAlAUfokcxADID2A5lQCQBEACQCmAGxHs8pdAF8ANBADu7AE4iAJgEI8AF2UBXIdL40ETItPqFLxKNABsUch24AxFQFsAhtu2eARiJCAMq6AJYAdpwQAG6eIgZ0ZoSMzBaI0kA=):

```C#
    public void M()
    {
        Log($"Hello {42}, world! {true}");
    }
    
    public static void Log(FormattableString value)
    {
    }
```

Gets compiled to:

```C#
    public void M()
    {
        object[] obj = new object[2];
        obj[0] = 42;
        obj[1] = true;
        Log(FormattableStringFactory.Create("Hello {0}, world! {1}", obj));
    }

    public static void Log(FormattableString value)
    {
    }
```

**Comment by damageboy** [comment]
OK, I should have realized it would probably be awful...

**Comment by ltrzesniewski** [comment]
Ok, it's maybe *a tiny bit* late, but interpolated string support is now available in v2, and does not allocate thanks to [interpolated string handlers](https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/) in C# 10. 🙂
