### ISSUE TITLE
Multiple loggers with same Name but different appenders

### ISSUE THREAD

**Issue by georgiosd** [Abc-Arbitrage/ZeroLog#25]
Hey guys

I'm trying to create a config file where I can write full logs (Debug) in one file and concise logs in another (Info).

But it seems that it will only match one of the appenders each time. Am I doing something wrong here?

```
{
  "Appenders": [
    {
      "Name": "CustomConsole",
      "AppenderTypeName": "ZeroLog.Appenders.ConsoleAppender",
      "AppenderJsonConfig": {
        "PrefixPattern": "[%level] @ %time - %logger :: "
      }
    },
    {
      "Name": "Console",
      "AppenderTypeName": "ZeroLog.Appenders.ConsoleAppender"
    },
    {
      "Name": "DebugFile",
      "AppenderTypeName": "ZeroLog.Appenders.DateAndSizeRollingFileAppender",
      "AppenderJsonConfig": {
        "FilePathRoot": "logs\\debug",
        "PrefixPattern": "[%level] @ %time - %logger :: "
      }
    },
    {
      "Name": "File",
      "AppenderTypeName": "ZeroLog.Appenders.DateAndSizeRollingFileAppender",
      "AppenderJsonConfig": {
        "FilePathRoot": "logs\\log",
        "PrefixPattern": "[%level] @ %time - %logger :: "
      }
    }
  ],
  "RootLogger": {
    "AppenderReferences": [
      "Console"
    ],
    "DefaultLevel": "Debug",
    "DefaultLogEventPoolExhaustionStrategy": "DropLogMessageAndNotifyAppenders"
  },
  "Loggers": [
    {
      "AppenderReferences": [
        "CustomConsole",
        "File"
      ],
      "Level": "Info",
      "Name": "BlackCat",
      "IncludeParentAppenders": false
    },
    {
      "AppenderReferences": [
        "DebugFile"
      ],
      "Level": "Debug",
      "Name": "BlackCat",
      "IncludeParentAppenders": false
    }
  ],
  "LogEventQueueSize": 1024,
  "LogEventBufferSize": 512
}
```

**Comment by ltrzesniewski** [comment]
Hi,

Multiple loggers with the same name aren't supported - we should throw an error there.

What we *could* support would be adding a "log level" configuration option at the appender level.

Thoughts? @rverdier @MendelMonteiro ?

**Comment by georgiosd** [comment]
That would be awesome!

Another choice for this use case would be to send messages discarded by level to the root logger

**Comment by ltrzesniewski** [comment]
We're thinking about changing the configuration format for the next major version, so the intent could be expressed more clearly. See #26.

We'd like to add a _level_ option on the _appender reference_, not on the appender itself, as that would enable more possibilities.

**Comment by ltrzesniewski** [comment]
You can now specify log levels in multiple places in v2 (appender, appender reference, logger configuration).
