### ISSUE TITLE
Change configuration format

### ISSUE THREAD

**Issue by ltrzesniewski** [Abc-Arbitrage/ZeroLog#26]
Let's agree on one thing: [JSON config files are a bad idea](https://arp242.net/weblog/json_as_configuration_files-_please_dont). Just [look at this](https://github.com/Abc-Arbitrage/ZeroLog/blob/6456cdf331ba832baf299c954c5e7dab6eb4d1e3/ZeroLog.json) - that's not very readable. 

Besides, our JSON schema is not very well designed. For instance, why do we have that [`AppenderJsonConfig`](https://github.com/Abc-Arbitrage/ZeroLog/blob/6456cdf331ba832baf299c954c5e7dab6eb4d1e3/src/ZeroLog/Config/AppenderDefinition.cs#L9) property? Do we need to be reminded we're using JSON?  
The overall design blocks potential features like #25, because it's not extensible enough.

We're not even using the JSON config feature internally at ABC arbitrage. This is telling. Let's design something better.

I made this issue to get some opinions on the matter.

Here are some proposals:

- Use an XML configuration similar to what log4net uses. This would be immediately familiar to log4net users, doesn't require a dependency on a parser, and tooling support for XML is quite good.
- Use an INI file. This is a very simple format that we can parse without any external library and doesn't require tooling at all. The downside is that it doesn't support hierarchical data, but I'm pretty sure we could design something that works.
- Use TOML, which is quite similar to INI, but with more features. It requires a parser though.
- Keep JSON, but change the schema to a better one.

Thoughts?

---

Here are some examples of what I'm thinking about. These are *not* definitive.

Example JSON (current status, for comparison):

```JSON
{
  "Appenders": [
    {
      "Name": "CustomConsole",
      "AppenderTypeName": "ZeroLog.Appenders.ConsoleAppender",
      "AppenderJsonConfig": { "PrefixPattern": "[%level] @ %time - %logger :: " }
    },
    {
      "Name": "Console",
      "AppenderTypeName": "ZeroLog.Appenders.ConsoleAppender"
    },
    {
      "Name": "File",
      "AppenderTypeName": "ZeroLog.Appenders.DateAndSizeRollingFileAppender",
      "AppenderJsonConfig": {
        "FilePathRoot": "zerolog",
        "PrefixPattern": "[%level] @ %time - %logger :: "
      }
    }
  ],
  "RootLogger": {
    "AppenderReferences": [
      "Console"
    ],
    "DefaultLevel": "Debug",
    "DefaultLogEventPoolExhaustionStrategy": "DropLogMessageAndNotifyAppenders"
  },
  "Loggers": [
    {
      "AppenderReferences": [
        "CustomConsole",
        "File"
      ],
      "Level": "Debug",
      "Name": "Foo.Something",
      "IncludeParentAppenders": false
    }
  ],
  "LogEventQueueSize": 1024,
  "LogEventBufferSize": 512

}
```

XML:

```XML
<zerolog>
    <parameters>
        <logEventQueueSize value="1024">
        <logEventBufferSize value="512">        
    </parameters>

    <appender name="CustomConsole" type="ZeroLog.Appenders.ConsoleAppender">
        <prefixPattern value="[%level] @ %time - %logger :: " />
    </appender>

    <appender name="Console" type="ZeroLog.Appenders.ConsoleAppender" />

    <appender name="File" type="ZeroLog.Appenders.DateAndSizeRollingFileAppender">
        <filePathRoot value="zerolog" />
        <prefixPattern value="[%level] @ %time - %logger :: " />
    </appender>

    <root>
        <level value="DEBUG" />
        <logEventPoolExhaustionStrategy value="DropLogMessageAndNotifyAppenders" />
        <appender-ref ref="Console" />
    </root>

    <logger name="Foo.Something" additivity="false">
        <level value="DEBUG" />
        <appender-ref ref="CustomConsole" />
        <appender-ref ref="File" />
    </logger>
</zerolog>
```

INI:

```INI

[Parameters]
LogEventQueueSize = 1024
LogEventBufferSize = 512

[Appender "CustomConsole"]
Type = ZeroLog.Appenders.ConsoleAppender
PrefixPattern = "[%level] @ %time - %logger :: "

[Appender "Console"]
Type = ZeroLog.Appenders.ConsoleAppender

[Appender "File"]
Type = ZeroLog.Appenders.DateAndSizeRollingFileAppender
FilePathRoot = zerolog
PrefixPattern = "[%level] @ %time - %logger :: "

[RootLogger]
Level = Debug
LogEventPoolExhaustionStrategy = DropLogMessageAndNotifyAppenders
AppenderRef = Console

[Logger "Foo.Something"]
Level = Debug
IncludeParentAppenders = false
AppenderRef = CustomConsole
AppenderRef = File
```

**Comment by ablanchet** [comment]
To me the INI version is way easier to apprehend and read. But the lack of hierarchy is very limiting, maybe not right now but maybe down the line ...

In my opinion a YAML format would be adequate. It's easy to read and quite easy to parse. I know it has [its down sides](https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html) but as long as we keep it simple enough in the configuration it could be a great fit.

**Comment by ltrzesniewski** [comment]
Hmmm... The [YAML spec](http://yaml.org/spec/1.2/spec.pdf) is 80 pages long... Not exactly something I'd call a simple format. But at least it solves the hierarchy issue. Still, I don't like the complexity.

And we already know we'll need more hierarchy. @ocoanet wanted to add a `level` config option on the appender reference to implement #25. I don't really know how it would look with INI files, but here's a possible solution:

```INI
[Logger "Foo.Something"]
Level = Debug
IncludeParentAppenders = false
AppenderRef = CustomConsole
AppenderRef.CustomConsole.Level = Info
AppenderRef = File
```
