### ISSUE TITLE
Improve LogManager shutdown

### ISSUE THREAD

**Issue by masm22** [Abc-Arbitrage/ZeroLog#27]
I faced an issue with `LogManager` disposal that I would like to have your advice on.

This is what we understand about `ZeroLog` disposal mechanisms:

* `LogManager` creates a foreground thread that will prevent the application from closing unless `LogManager.Shutdown()` is called.
* During `Shutdown()` `LogManager` will replace itself with `_noOpLogManager` and then will dispose the memory buffer used by loggers. Thus, all subsequent calls for `GetLogger` will receive a dummy logger instance that does void call.
* at the same time all previously acquired loggers if called after `Shutdown` will try to write to disposed memory and generate `AccessViolationException`

Could you please comment on the following two questions:

1. Since you have `_noOpLogManager` I assume that you have considered the case when logger might be called after `Shutdown()`. What was your idea about loggers that are saved as references in application? The only possibility I see is to convert them to no-op loggers before disposing the buffer. But it looks like `LogManager` does not store the references to its loggers so cannot disable them during shutdown.
2. Is there any reason for `LogManager`  to use foreground thread? If it was background, than logger could live all application lifetime and all resources will be disposed by CLR when process terminates.

Thanks.

**Comment by ltrzesniewski** [comment]
Thanks for the report. It looks like the shutdown scenario is not as polished as it should be. Access violations are definitely unacceptable, and some work should be done here.

Until this is fixed, you should call `Shutdown` as the last action of your application, just before it exits.

The no-op implementation is there just to handle uninitialized state without throwing, we never intended it to be used after shutdown.

Loggers were designed to be saved preferably in `static` fields and kept until the end of the process.

I think the logging thread was made foreground to allow it to flush the remaining  messages before the process exits. I'm not sure if we could ensure that with a background thread, especially on the `netstandard2.0` target. We'll see what we can do.

**Comment by masm22** [comment]
Thank you for your comment. I'll describe our scenario in more detail to give you more insight.

We have a set of NUnit tests for component that uses `ZeroLog`. `ReSharper` will run those in a separate AppDomain. In order for the tests process to terminate we use `[TestFixtureShutdown]` where we call `Shutdown` on `LogManager`. Otherwise the foreground thread will prevent the process from terminating. Our component is subscribed to `DomainUnload` event where it is doing some logging to `ZeroLog` (disposed by now).

I described the case for AppDomain but it looks like process will have the same problems if it does not disable all services that do logging prior to calling `LogManager.Shutdown()` which might be complicated.

**Comment by ltrzesniewski** [comment]
Ok I see, thanks for the details.

I'll check this in our codebase Monday, but IIRC we simply don't initialize ZeroLog when testing our own components that use it. Is there a reason you initialize it?
