### ISSUE TITLE
Does it run in AOT? Does it run with no proper msbuild support?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Abc-Arbitrage/ZeroLog#29]
1. Does it generates code during startup? If yes, then AOT is not supported (Xamarin iOS, Unity IL2CPP)
2. Does it requires msbuild task to work? Or can work from csx or manuals Roslyn compiler invocation or Unity project with custom build tooling?

Please document.

**Comment by ltrzesniewski** [comment]
1. Yes, it generates code dynamically on startup
2. There are no additional MSBuild tasks

**Comment by ltrzesniewski** [comment]
Note that we *could* provide an alternate (slower) path to dynamically generated code, but we'd need a way to test that in CI.
