### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by malusev998** [Abc-Arbitrage/ZeroLog#42]
Thanks for this library, it really looks good, but i think there is naming collision with existing library.
[Go Zerolog](https://github.com/rs/zerolog) -> Logging library for GO. These two libraries do the same thing and have same name but for different programming languages, maybe you should get in touch with the author of the go library.

**Comment by MendelMonteiro** [comment]
Technically ZeroLog was the existing library and they collided with us ;-)

I'm not sure @rs would change the name of their library and I'm pretty sure we wouldn't.  I think that with the prefix of who the repository belongs to it's pretty clear that they are not the same library.  Also they won't show up in the same package management tools as they exist in different ecosystems.

**Comment by rs** [comment]
Wow, I felt creative with the name at the time, but apparently, I wasn't ;)

As @MendelMonteiro said, I doubt the name collision would be an issue.
