### ISSUE TITLE
Support exception argument when logging Errors

### ISSUE THREAD

**Issue by MendelMonteiro** [Abc-Arbitrage/ZeroLog#5]
Tricky to figure out how to do this without allocating.  Most exceptions will be allocated anyways by the thrower however they can also be cached in which case they won't incur an allocation.

**Comment by rverdier** [comment]
I would be in favor of simply generating log4net-ish overloads in the t4 file, for the sole purpose of easing an eventual migration from more mainstream libraries, even if I'm not completely sold about that idea.

I think that logging an exception should be considered, well, exceptional, and I fail to see how we could reasonably provide a way to do so without allocating anything.

I don't have a strong opinion about that yet, but the more I think about it, the more I think ZeroLog should be as explicit as possible regarding the guarantees it offers. I would be in favor of keeping the public surface API small, and letting people decide how they want to handle exceptional cases up front. We probably won't try to offer as much options as other libraries regarding exception logging anyways (layout templating, messages, stack traces, etc.).

**Comment by MendelMonteiro** [comment]
Done a while ago
