### ISSUE TITLE
How to display local time and thread name in the log?

### ISSUE THREAD

**Issue by ooosan** [Abc-Arbitrage/ZeroLog#64]
LogManager.Initialize(new ZeroLogConfiguration
                {
                    LogMessagePoolSize = 1024,

                    RootLogger =
                {
                    LogMessagePoolExhaustionStrategy = LogMessagePoolExhaustionStrategy.Allocate,
                    Appenders =
                        {
                            new DateAndSizeRollingFileAppender(filePath)
                            {
                                FileNamePrefix = "zerolog" ,
                                Formatter=new DefaultFormatter
                                {
                                     PrefixPattern = "%time %level %thread %logger||"
                                }
                            }
                        }
                }
                });
I used this code, which displayed UTC time and thread ID, but I want to display local time and thread name.

**Comment by ltrzesniewski** [comment]
> I want to display local time

ZeroLog only handles UTC dates currently, but I suppose local time could be added as a new feature easily (just need to check the conversion doesn't allocate).

> and thread name

The thread name should already be displayed, unless the thread is not named, in which case the thread id will be used.

**Comment by ltrzesniewski** [comment]
New `%localDate` and `%localTime` placeholders are now available in v2.2.0
