### ISSUE TITLE
Why do I get such strange results when I use benchmark testing for zerolog?

### ISSUE THREAD

**Issue by ooosan** [Abc-Arbitrage/ZeroLog#65]
This is my test code:

        [GlobalSetup]
        public static void GlobalSetup()
        {
            InitZeroLog();
        }

        private static readonly ZeroLog.Log _log = LogManager.GetLogger(typeof(BenchMarkTest));

        private static void InitZeroLog()
        {
            string filePath = @"G:\000\dotnet_benchmark\BenchmarkTest\framworkTest\logs";
            var n = new ZeroLogConfiguration()
            {
                LogMessagePoolSize = 5000,
                LogMessageBufferSize = 128,
                AutoRegisterEnums = true,
                AppenderQuarantineDelay = TimeSpan.Zero,
                RootLogger =
                {
                    LogMessagePoolExhaustionStrategy = LogMessagePoolExhaustionStrategy.Allocate,
                    Appenders =
                        {
                            new DateAndSizeRollingFileAppender(filePath)
                            {
                                FileNamePrefix = "zerolog" ,
                                Formatter=new DefaultFormatter
                                {
                                     PrefixPattern = "%time %level %thread "
                                }
                            }
                    }
                }
            };
            LogManager.Initialize(n);
            
        }

        [Benchmark]
        [InvocationCount(200)]
        [IterationCount(5000)]
        public void ZeroLogStringRecord()
        {
            _log.Info("test message");
        }

This is result:
![MQTODO7)ULWSIS9P2HX$}`0](https://github.com/user-attachments/assets/817d2458-e161-49bf-92bf-e33cb1699798)

Why is there such a large difference between the maximum and minimum values of zerolog? I expect logging a single log entry in C# to ideally take around 50ns, whereas in C++, logging a log entry takes only 10ns.

I've found that the most time-consuming section in zerolog is this part:

    public bool TryAcquire([MaybeNullWhen(false)] out T instance)
    {
        var cached = Interlocked.Exchange(ref _cached, null);
        if (cached is not null)
        {
            instance = cached;
            return true;
        }
        
        if (_queue.TryDequeue(out instance))
        {
            Interlocked.Decrement(ref _queueCount);
            return true;
        }

        return false;
    }

but it doesn't seem like there's anything to change.

**Comment by ltrzesniewski** [comment]
My first thought is that this may be due to allocations: when you log something, ZeroLog will:
- acquire a message from the preallocated pool (`LogMessagePoolSize = 5000`)
- fill it with the relevant values (the logger, timestamp, level and `"test message"`)
- send it to the appender thread to be formatted (`DefaultFormatter`) and output (`DateAndSizeRollingFileAppender`).

In your case, you have specified `LogMessagePoolExhaustionStrategy = LogMessagePoolExhaustionStrategy.Allocate` which will allow ZeroLog to allocate when the message pool is empty, which can cause the GC to stop the benchmark at any time and cause delays. I know it looks like it's not supposed to happen since you've set `[InvocationCount(200)]` which is lower than the pool size, but due to the multithreaded design, you need to call `LogManager.Flush()` in an `[IterationCleanup]` method in order to ensure the queue has been flushed and is empty for the next iteration, and that all file streams have been flushed as well.

---

But now, let's try benchmarking instead of guessing. 🙂 

Here's what I'm getting with your benchmark almost as-is (with `[MemoryDiagnoser, AllStatisticsColumn]` and the `filePath` changed):

```
BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3958/23H2/2023Update/SunValley3)
13th Gen Intel Core i9-13900K, 1 CPU, 32 logical and 24 physical cores
.NET SDK 9.0.100-preview.3.24204.13
  [Host]     : .NET 8.0.6 (8.0.624.26715), X64 RyuJIT AVX2
  Job-JCHJRX : .NET 8.0.6 (8.0.624.26715), X64 RyuJIT AVX2

InvocationCount=200  IterationCount=5000  UnrollFactor=1

| Method              | Mean     | Error    | StdDev   | StdErr   | Median   | Min      | Q1       | Q3       | Max      | Op/s         | Allocated |
|-------------------- |---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|-------------:|----------:|
| ZeroLogStringRecord | 80.06 ns | 0.498 ns | 9.988 ns | 0.151 ns | 81.50 ns | 55.00 ns | 75.00 ns | 86.00 ns | 107.5 ns | 12,490,034.2 |       2 B |
```

Well, apparently that's not because of allocations. 😅 

Now, let's add:

```csharp
[IterationCleanup]
public void IterationCleanup()
    => LogManager.Flush();
```

```
| Method              | Mean     | Error    | StdDev   | StdErr   | Median   | Min      | Q1       | Q3       | Max      | Op/s         | Allocated |
|-------------------- |---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|-------------:|----------:|
| ZeroLogStringRecord | 75.79 ns | 1.182 ns | 25.21 ns | 0.359 ns | 62.50 ns | 46.00 ns | 53.50 ns | 98.00 ns | 166.0 ns | 13,193,543.6 |       2 B |
```

Now, let's replace `[InvocationCount]` with `OperationsPerInvoke` (best practice):

```csharp
[Benchmark(OperationsPerInvoke = 200)]
[IterationCount(5000)]
public void ZeroLogStringRecord()
{
    for (var i = 0; i < 200; ++i)
        _log.Info("test message");
}
```

```
| Method              | Mean     | Error    | StdDev   | StdErr   | Median   | Min      | Q1       | Q3       | Max      | Op/s         | Allocated |
|-------------------- |---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|-------------:|----------:|
| ZeroLogStringRecord | 70.52 ns | 0.987 ns | 20.75 ns | 0.300 ns | 59.50 ns | 46.00 ns | 55.00 ns | 89.50 ns | 146.5 ns | 14,180,847.3 |       2 B |
```

Now you're right, there's still a large difference between the min and max. If I reduce the iteration count to 500, I get this graph:

```
TestBench.ZeroLogStringRecord: Job-ZWWNHL(InvocationCount=1, IterationCount=500, UnrollFactor=1)
Runtime = .NET 8.0.6 (8.0.624.26715), X64 RyuJIT AVX2; GC = Concurrent Workstation
Mean = 108.139 ns, StdErr = 2.166 ns (2.00%), N = 497, StdDev = 48.298 ns
Min = 46.000 ns, Q1 = 54.500 ns, Median = 98.000 ns, Q3 = 152.500 ns, Max = 280.000 ns
IQR = 98.000 ns, LowerFence = -92.500 ns, UpperFence = 299.500 ns
ConfidenceInterval = [100.967 ns; 115.310 ns] (CI 99.9%), Margin = 7.172 ns (6.63% of Mean)
Skewness = 0.29, Kurtosis = 1.96, MValue = 5.09
-------------------- Histogram --------------------
[ 45.247 ns ;  61.253 ns) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 61.253 ns ;  77.253 ns) | @@@@@@@@@
[ 77.253 ns ;  89.997 ns) | @@@@@@
[ 89.997 ns ; 106.003 ns) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[106.003 ns ; 122.253 ns) | @@@@@@@@@@@@@@@@@@@@@@@
[122.253 ns ; 132.747 ns) | @@@@@@@@@@@@
[132.747 ns ; 148.997 ns) | @@@@@@@@@@@@@@@@@@@@@@@@@
[148.997 ns ; 165.003 ns) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[165.003 ns ; 175.497 ns) | @@@@@@@@@@@@@@@@@@@@@
[175.497 ns ; 191.503 ns) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[191.503 ns ; 204.497 ns) | @
[204.497 ns ; 220.503 ns) | @@@@
[220.503 ns ; 236.509 ns) |
[236.509 ns ; 252.514 ns) |
[252.514 ns ; 271.997 ns) |
[271.997 ns ; 288.003 ns) | @
---------------------------------------------------
```

So there's definitely a multimodal distribution. Maybe that's due to the I/O? Let's replace the appender by this, and go back to 5000 iterations:

```csharp
public sealed class NullAppender : StreamAppender
{
    public NullAppender()
    {
        // Make sure the message is rendered
        Stream = Stream.Null;
    }
}
```

```csharp
new NullAppender
{
    Formatter = new DefaultFormatter
    {
        PrefixPattern = "%time %level %thread "
    }
}
```

```
| Method              | Mean     | Error    | StdDev   | StdErr   | Median   | Min      | Q1       | Q3       | Max      | Op/s         | Allocated |
|-------------------- |---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|-------------:|----------:|
| ZeroLogStringRecord | 62.99 ns | 0.907 ns | 19.29 ns | 0.276 ns | 52.50 ns | 44.00 ns | 49.50 ns | 82.00 ns | 133.0 ns | 15,875,612.4 |         - |
```

So, there's still a difference between min and max, and the standard deviation is about the same, so it's not file I/O apparently.

Maybe let's increase the operations per invoke to 50k and let BDN decide about the iteration count?

```
| Method              | Mean     | Error    | StdDev   | StdErr   | Min      | Q1       | Median   | Q3       | Max      | Op/s         | Allocated |
|-------------------- |---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|-------------:|----------:|
| ZeroLogStringRecord | 85.15 ns | 5.052 ns | 14.74 ns | 1.489 ns | 57.24 ns | 73.87 ns | 86.30 ns | 93.90 ns | 119.0 ns | 11,743,536.5 |         - |

// * Warnings *
MinIterationTime
  TestBench.ZeroLogStringRecord: InvocationCount=1, UnrollFactor=1 -> The minimum observed iteration time is 2.8624 ms which is very small. It's recommended to increase it to at least 100.0000 ms using more operations.
```

So, yeah. In any case, we're measuring *nanoseconds*, which is not terribly accurate. BDN even complains that we should make the benchmark *slower*. And it did so for every benchmark. 😅 

So, let's just do that with one million operations per invocation:

```
| Method              | Mean     | Error   | StdDev  | StdErr  | Min      | Q1       | Median   | Q3       | Max      | Op/s        | Allocated |
|-------------------- |---------:|--------:|--------:|--------:|---------:|---------:|---------:|---------:|---------:|------------:|----------:|
| ZeroLogStringRecord | 125.1 ns | 3.41 ns | 9.38 ns | 1.00 ns | 104.7 ns | 117.4 ns | 124.7 ns | 131.1 ns | 149.4 ns | 7,995,274.4 |         - |
```

But now, the I/O definitely starts to play a role... but at least the min/max are closer and BDN doesn't complain. 🙂 

Here's the code I used for this one:

```csharp
using System;
using System.IO;
using BenchmarkDotNet.Attributes;
using ZeroLog.Appenders;
using ZeroLog.Configuration;
using ZeroLog.Formatting;

namespace ZeroLog.Benchmarks;

[MemoryDiagnoser]
[AllStatisticsColumn]
public class TestBench
{
    [GlobalSetup]
    public static void GlobalSetup()
    {
        InitZeroLog();
    }

    private static readonly ZeroLog.Log _log = LogManager.GetLogger(typeof(TestBench));

    private static void InitZeroLog()
    {
        string filePath = @"C:\Dev\Temp\ZeroLog";
        var n = new ZeroLogConfiguration()
        {
            LogMessagePoolSize = 1_000_000,
            LogMessageBufferSize = 128,
            AutoRegisterEnums = true,
            AppenderQuarantineDelay = TimeSpan.Zero,
            RootLogger =
            {
                LogMessagePoolExhaustionStrategy = LogMessagePoolExhaustionStrategy.Allocate,
                Appenders =
                {
                    new DateAndSizeRollingFileAppender(filePath)
                    {
                        FileNamePrefix = "zerolog",
                        Formatter = new DefaultFormatter
                        {
                            PrefixPattern = "%time %level %thread "
                        }
                    }
                    // new NullAppender
                    // {
                    //     Formatter = new DefaultFormatter
                    //     {
                    //         PrefixPattern = "%time %level %thread "
                    //     }
                    // }
                }
            }
        };
        LogManager.Initialize(n);
    }

    [Benchmark(OperationsPerInvoke = 1_000_000)]
    // [IterationCount(5000)]
    public void ZeroLogStringRecord()
    {
        for (var i = 0; i < 1_000_000; ++i)
            _log.Info("test message");
    }

    [IterationCleanup]
    public void IterationCleanup()
        => LogManager.Flush();
}

public sealed class NullAppender : StreamAppender
{
    public NullAppender()
    {
        // Make sure the message is rendered
        Stream = Stream.Null;
    }
}
```

**Comment by ltrzesniewski** [comment]
Oh, I forgot to mention that `DateAndSizeRollingFileAppender` will allocate when rolling files, and this benchmark easily produces several rolls, as the default config is to roll every 200MB.

But I think the main conclusion here is to pay attention to the BDN warnings, particularly given that benchmarking really short operations is hard.

I'm closing this now, but feel free to comment if you have further questions.
